#!/usr/bin/env python3
# -*- coding: utf-8 -*

import os
import sys

sys.path.insert(0, os.path.abspath(os.path.dirname(__file__) + '/../lib/python'))

import wither.backup

if __name__ == '__main__':
  wither.backup.init()
  sys.exit(wither.backup.main())

##
# vim: ts=2 sw=2 et fdm=marker :
##
